@apiUrl = https://amigo-api.zhaobg.com
@user = root
@psw = Amigo@Abcd1234

### get session
GET {{apiUrl}}/session/token

### user login
# @name login
POST {{apiUrl}}/user/login?_format=json HTTP/1.1
content-type: application/json

{"name": "{{user}}","pass": "{{psw}}"}

###
@logoutToken = {{login.response.body.logout_token}}

###
@csrfToken = {{login.response.body.csrf_token}}

### get user status
GET {{apiUrl}}/user/login_status?_format=json HTTP/1.1

### get user profile
GET {{apiUrl}}/api/v1/accountProfile

### user logout
POST {{apiUrl}}/user/logout?_format=json&token={{logoutToken}} HTTP/1.1
Content-type: application/json
withCredentials: true


### get flagging
GET {{apiUrl}}/api/v1/flagging/favorite/c85a3af6-6d2d-4c88-81bc-42c5e53b490e

### filter flagging
GET {{apiUrl}}/api/v1/flagging/favorite?filter[uid.id]={{user_uuid}}&filter[entity_id]=825

### flag payment
GET {{apiUrl}}/api/v1/flagging/payment

### check node paymented
GET {{apiUrl}}/api/v1/flagging/payment?filter[uid.id]=505d9929-18cc-496d-8750-2aa1d2a72c65&filter[entity_id]=35

### POST flagging
POST {{apiUrl}}/api/v1/flagging/favorite
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

{
  "data": {
    "type": "flagging--favorite",
    "attributes": {
      "entity_type": "node",
      "entity_id": "1302",
      "global": false
    },
    "relationships": {
      "flagged_entity": {
        "data": {
          "type": "node--question",
          "id": "8aae1766-38d7-4690-af3a-77b099e56e85"
        }
      },
      "uid": {
        "data": {
          "type": "user--user",
          "id": "15765815-07f2-4d7d-8142-cb598f82af2e"
        }
      }
    }
  }
}

### delete flagging
DELETE {{apiUrl}}/api/v1/flagging/favorite/ba70cd3c-7bd7-48c2-9aa5-07b175d8f4d7
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}
