### https://www.drupal.org/docs/8/core/modules/rest/javascript-and-drupal-8-restful-web-services#s-login
@apiUrl = https://amigo-api.zhaobg.com
@user = root
@psw = Amigo@Abcd1234
@user_uuid = 15765815-07f2-4d7d-8142-cb598f82af2e
@node_uuid = 97edbdba-16a9-4e48-9285-9a2854968cf7

### get session
GET {{apiUrl}}/session/token

### user login
# @name login
POST {{apiUrl}}/user/login?_format=json HTTP/1.1
content-type: application/json

{"name": "{{user}}","pass": "{{psw}}"}

###
@logoutToken = {{login.response.body.logout_token}}

###
@csrfToken = {{login.response.body.csrf_token}}

### get user status
GET {{apiUrl}}/user/login_status?_format=json HTTP/1.1

### get user profile
GET {{apiUrl}}/api/v1/accountProfile

### user logout
POST {{apiUrl}}/user/logout?_format=json&token={{logoutToken}} HTTP/1.1
Content-type: application/json
withCredentials: true

### logout v2 强制退出
POST {{apiUrl}}/user/logout HTTP/1.1

### get all api
GET {{apiUrl}}/api/v1
