### https://www.drupal.org/docs/8/core/modules/rest/javascript-and-drupal-8-restful-web-services#s-login
@apiUrl = https://teslacig-admin.zhaobg.com
@user = root
@psw = Abcd#1234@Teslacig
@user_uuid = 15765815-07f2-4d7d-8142-cb598f82af2e
@node_uuid = 97edbdba-16a9-4e48-9285-9a2854968cf7

### get session
GET {{apiUrl}}/session/token

### user login
# @name login
POST {{apiUrl}}/user/login?_format=json HTTP/1.1
content-type: application/json

{"name": "{{user}}","pass": "{{psw}}"}

###
@logoutToken = {{login.response.body.logout_token}}

###
@csrfToken = {{login.response.body.csrf_token}}

### get user status
GET {{apiUrl}}/user/login_status?_format=json HTTP/1.1

### get user profile
GET {{apiUrl}}/api/v1/accountProfile

### user logout
POST {{apiUrl}}/user/logout?_format=json&token={{logoutToken}} HTTP/1.1
Content-type: application/json
withCredentials: true

### logout v2 强制退出
POST {{apiUrl}}/user/logout HTTP/1.1

### get all api
GET {{apiUrl}}/api/v1

### create landing
POST {{apiUrl}}/api/v3/landingPage/builder
Content-type: application/json
withCredentials: true
X-CSRF-Token: {{csrfToken}}

{
  "title": "着陆页",
  "body": [
    {
      "type": "text",
      "spacer": "md",
      "body": "信使UI是基于 Material 的 Angular 前端框架， 五十多个丰富的组件可提供优秀的数字创新体验，使用 Web Builder 可以通过拖拽快速构建响应式、多主题的 Web 页面。Builder 与众不同的是它完全融入到了 <strong class=\"text-primary\">Storybook</strong> 当中，它是一个面向UI组件开发的工具，提供了组件驱动的开发方式、交互式展示和测试界面，以及文档化功能。",
      "title": {
        "label": "欢迎使用 <strong class=\"text-primary\">Web Builder</strong> 快速构建页面",
        "style": "style-v1",
        "classes": "mat-display-2 bold"
      },
      "bg": {
        "classes": "bg- bg-fill-width"
      },
      "classes": "text-center",
      "actionsAlign": "center center",
      "actions": [
        {
          "type": "btn",
          "mode": "raised",
          "color": "primary",
          "href": "/builder",
          "label": "开始体验"
        }
      ]
    }
  ],
  "time": "2023-11-09T15:12:31.062Z"
}
