@apiUrl = https://amigo-api.zhaobg.com
@user = root
@psw = Amigo@Abcd1234

### get session
GET {{apiUrl}}/session/token

### user login
# @name login
POST {{apiUrl}}/user/login?_format=json HTTP/1.1
content-type: application/json

{"name": "{{user}}","pass": "{{psw}}"}

###
@logoutToken = {{login.response.body.logout_token}}

###
@csrfToken = {{login.response.body.csrf_token}}

### get user status
GET {{apiUrl}}/user/login_status?_format=json HTTP/1.1

### get user profile
GET {{apiUrl}}/api/v1/accountProfile

### user logout
POST {{apiUrl}}/user/logout?_format=json&token={{logoutToken}} HTTP/1.1
Content-type: application/json
withCredentials: true


### wechat
POST {{apiUrl}}/api/v1/miniprogram/login?_format=json
Content-Type: application/x-www-form-urlencoded
