@base = https://nnitpai-cms.zhaobg.com
@user = test
@psw = test

### user login
# @name login
POST {{base}}/user/login?_format=json HTTP/1.1
content-type: application/json

{"name": "{{user}}","pass": "{{psw}}"}

###

@logoutToken = {{login.response.body.logout_token}}

### get user status
GET {{base}}/user/login_status?_format=json HTTP/1.1

### user logout
POST {{base}}/user/logout?_format=json&token={{logoutToken}} HTTP/1.1

### logout v2
POST {{base}}/user/logout HTTP/1.1

### get user info
GET {{base}}/jsonapi/user/user?filter[drupal_internal__uid]={{login.response.body.current_user.uid}}

### get all api
GET {{base}}/jsonapi

### get all user
GET {{base}}/jsonapi/user/user




