### https://www.drupal.org/docs/8/core/modules/rest/javascript-and-drupal-8-restful-web-services#s-login
@apiUrl = https://api.lvxinyun.com
@user = root
@psw = Abcd#1234@nn
@user_uuid = 15765815-07f2-4d7d-8142-cb598f82af2e
@node_uuid = 97edbdba-16a9-4e48-9285-9a2854968cf7

### user login
# @name login
POST {{apiUrl}}/user/login?_format=json HTTP/1.1
content-type: application/json

{"name": "{{user}}","pass": "{{psw}}"}

###
@logoutToken = {{login.response.body.logout_token}}

###
@csrfToken = {{login.response.body.csrf_token}}

### get user status
GET {{apiUrl}}/user/login_status?_format=json HTTP/1.1

### get user profile
GET {{apiUrl}}/api/v1/accountProfile

### user logout
POST {{apiUrl}}/user/logout?_format=json&token={{logoutToken}} HTTP/1.1
Content-type: application/json
withCredentials: true
### logout v2 强制退出
POST {{apiUrl}}/user/logout HTTP/1.1

### get all roles
GET {{apiUrl}}/api/v1/user_role/user_role

### get user uuid
GET {{apiUrl}}/api/v1/user/user?filter[drupal_internal__uid]={{login.response.body.current_user.uid}}

### get user
GET {{apiUrl}}/api/v1/user/user?filter[drupal_internal__uid]={{login.response.body.current_user.uid}}&include=user_picture

### get all api
GET {{apiUrl}}/api/v1

### get all user
GET {{apiUrl}}/api/v1/user/user

### https://www.drupal.org/docs/core-modules-and-themes/core-modules/api/v1-module/api-overview
### https://explore.api/v1.dev/


### taxonomy
GET {{apiUrl}}/api/v1/node/recruitment/5c67b19c-b8c4-495b-8a6f-1bea1a852a49/skill?resourceVersion=id%3A90

### taxonomy skill
GET {{apiUrl}}/api/v1/taxonomy_term/search_category

### https://dev.acquia.com/blog/decoupling-drupal-8-with-json-api/15/05/2018/19596

@type=article

### get need set header Accept: application/vnd.api+json

### get node list
GET {{apiUrl}}/api/v1/node/news?include=category,field_tags,media,media.field_media_image&sort=-changed&jsonapi_include=1&page[limit]=1

### get single resource
GET {{apiUrl}}/api/v1/node/{{type}}/b59a2767-89b8-418d-91fe-6f0e6a5638ec
### get collections rsource
GET {{apiUrl}}/api/v1/node/{{type}}

### get collections limit
GET {{apiUrl}}/api/v1/node/{{type}}?page[limit]=10

### get collections offset
GET {{apiUrl}}//api/v1/node/{{type}}?page[limit]=25&page[offset]=25

### sort by title or -title
GET {{apiUrl}}/api/v1/node/{{type}}?sort=title

### sort by nid or -nid
{{apiUrl}}/api/v1/node/{{type}}?sort=nid

### get case fields what you want
GET {{apiUrl}}/api/v1/node/{{type}}?fields[node--{{type}}]=title,field_image,field_tags&include=field_image,field_tags&fields[file--file]=uri&fields[taxonomy_term--industry]=name
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

### get job fields what you want
GET {{apiUrl}}/api/v1/node/{{type}}?fields[node--{{type}}]=title,created,changed,body,deadline,number,salary,work_experience,skill,education,company&include=skill,education,company,company.logo&fields[taxonomy_term--skill]=name&fields[taxonomy_term--education]=name&fields[node--company]=title,address,phone,welfare,logo&fields[file--file]=uri
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

### get node by term
GET {{apiUrl}}/api/v1/node/article?fields[node--article]=title,changed,drupal_internal__nid,path&include=search_category&jsonapi_include=1

### get question with comment relation user
GET {{apiUrl}}/api/v1/node/question?fields[node--question]=title,changed,path,drupal_internal__nid,answer,uid&include=uid,uid.user_picture&fields[user--user]=name,user_picture&fields[file--file]=uri&jsonapi_include=1

### get question comment by user
GET {{apiUrl}}/api/v1/comment/answer?filter[uid.id]=d5fb03cb-abca-43ba-baa5-a162a576e67a&filter[entity_id.id]=18dac740-1d11-43c0-a431-d2b9e402fe6b&sort=-created&page[limit]=1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

### all post, patch, delete need set header
### Accept: application/vnd.api+json
### Content-Type: application/vnd.api+json
### 'X-CSRF-Token'
### 需要注意字段必须包含所有的必填项

@sample_type = question
@article_node_uuid = bb0617db-af29-4239-b824-4131f29d7530

### creating node // no need with relationship
POST {{apiUrl}}/api/v1/node/{{sample_type}} HTTP/1.1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

{
  "data": {
    "type": "node--{{sample_type}}",
    "attributes": {
      "title": "new article by Johnson xxx",
      "body": {
        "value": "Hello world! Lorem ipsum dolor sit amet consectetur adipiscing elit",
        "format": "plain_text"
      }
    }
  }
}

### update single node
PATCH {{apiUrl}}/api/v1/node/article/{{article_node_uuid}}
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

{
  "data": {
    "type": "node--article",
    "id": "{{article_node_uuid}}",
    "attributes": {
      "title": "update the article",
    },
    "relationships": {
      "uid": {
        "data": {
          "type": "user--user",
          "id": "{{user_uuid}}"
        }
      }
    }
  }
}


### delete single node
DELETE {{apiUrl}}/api/v1/node/article/{{article_node_uuid}}
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}


### post question comment
POST {{apiUrl}}/api/v1/comment/answer
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

{
  "data":{
    "type": "comment--answer",
    "attributes":{
      "entity_type":"node",
      "field_name":"answer",
      "content":{
        "value":"New comment by johnson!",
        "format":"plain_text"
      }
    },
    "relationships":{
      "comment_type":{
        "data":{
          "type":"comment_type--comment_type",
          "id":"a395ac8e-3c9a-43d5-8ec8-cea74116d5f3"
        }
      },
      "entity_id":{
        "data":{
          "type":"node--question",
          "id":"18dac740-1d11-43c0-a431-d2b9e402fe6b"
        }
      }
    }
  }
}

### update comment
PATCH {{apiUrl}}/api/v1/comment/answer/92e32979-ebbd-494c-aabe-6a1f9a6b505d
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

{
  "data": {
    "type": "comment--answer",
    "id": "92e32979-ebbd-494c-aabe-6a1f9a6b505d",
    "attributes": {
      "content": {
        "value": "Updated body text",
        "format": "full_html",
      }
    },
    "relationships": {
      "uid": {
        "data": {
          "type": "user--user",
          "id": "d5fb03cb-abca-43ba-baa5-a162a576e67a"
        }
      }
    }
  }
}

### get user
GET {{apiUrl}}/api/v1/file/file

### test
GET {{apiUrl}}/api/v1/comment/comment?filter[entity_id.id]=18dac740-1d11-43c0-a431-d2b9e402fe6b&include=uid,uid.user_picture&fields[user--user]=name,user_picture&fields[file--file]=uri,url&sort=-created&jsonapi_include=1

### get lxy
GET https://lxyapi.zhaobg.com/api/v1/content?six-point=217


### get flagging
GET {{apiUrl}}/api/v1/flagging/favorite/c85a3af6-6d2d-4c88-81bc-42c5e53b490e

### filter flagging
GET {{apiUrl}}/api/v1/flagging/favorite?filter[uid.id]={{user_uuid}}&filter[entity_id]=825

### flag payment
GET {{apiUrl}}/api/v1/flagging/payment

### check node paymented
GET {{apiUrl}}/api/v1/flagging/payment?filter[uid.id]=505d9929-18cc-496d-8750-2aa1d2a72c65&filter[entity_id]=35

### POST flagging
POST {{apiUrl}}/api/v1/flagging/favorite
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

{
  "data": {
    "type": "flagging--favorite",
    "attributes": {
      "entity_type": "node",
      "entity_id": "1302",
      "global": false
    },
    "relationships": {
      "flagged_entity": {
        "data": {
          "type": "node--question",
          "id": "8aae1766-38d7-4690-af3a-77b099e56e85"
        }
      },
      "uid": {
        "data": {
          "type": "user--user",
          "id": "15765815-07f2-4d7d-8142-cb598f82af2e"
        }
      }
    }
  }
}

### delete flagging
DELETE {{apiUrl}}/api/v1/flagging/favorite/ba70cd3c-7bd7-48c2-9aa5-07b175d8f4d7
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

### get taxonomy
GET {{apiUrl}}/taxonomy/term/30?category=28

### wechat
POST {{apiUrl}}/api/v1/miniprogram/login?_format=json
Content-Type: application/x-www-form-urlencoded

### 咨询变量
@consultType = consult
@consultID = dfc8256d-7526-480a-b354-06d584204537

### 案源广场 - 全部
GET {{apiUrl}}/api/v1/node/consult?fields[node--consult]=title,uid,changed,consult_answer,field_tags,moderation_state&include=uid,uid.user_picture,field_tags&fields[taxonomy_term--consult_type]=name&fields[user--user]=name,user_picture&fields[file--file]=uri,url&jsonapi_include=1&page[limit]=10

### 某个咨询的全部回复
GET {{apiUrl}}/api/v1/comment/consult_answer?filter[entity_id.id]=dfc8256d-7526-480a-b354-06d584204537&include=uid,uid.user_picture&fields[user--user]=name,user_picture&fields[file--file]=uri,url&sort=-created&filter[status]=1&jsonapi_include=1

### 获取待发布咨询
GET {{apiUrl}}/api/v1/node/consult?fields[node--consult]=title,uid,changed,consult_answer,field_tags&include=uid,uid.user_picture,field_tags&fields[taxonomy_term--consult_type]=name&fields[user--user]=name,user_picture&fields[file--file]=uri,url&filter[assist_moderation_state]=draft&jsonapi_include=1

### 获取咨询已回复的node
GET {{apiUrl}}/api/v1/node/consult?fields[node--consult]=title,uid,changed,consult_answer,field_tags&include=uid,uid.user_picture,field_tags&fields[taxonomy_term--consult_type]=name&fields[user--user]=name,user_picture&fields[file--file]=uri,url&jsonapi_include=1

### 查看某个用户的发布的咨询的回复数
GET {{apiUrl}}/api/v1/node/consult

### 回复某个咨询
POST {{apiUrl}}/api/v1/comment/consult_answer
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

{
  "data":{
    "type": "comment--consult_answer",
    "attributes":{
      "entity_type":"node",
      "field_name":"consult_answer",
      "content":{
        "value":"{{回复咨询的内容}}",
        "format":"plain_text"
      }
    },
    "relationships":{
      "comment_type":{
        "data":{
          "type":"comment_type--comment_type",
          "id": "662120d4-c423-4b1e-a221-5b4bb906fcf9"
        }
      },
      "entity_id":{
        "data":{
          "type":"node--consult",
          "@id":"当前node的id",
          "id":"dfc8256d-7526-480a-b354-06d584204537"
        }
      }
    }
  }
}

### 全部咨询
GET {{apiUrl}}/api/v1/node/consult

### 发布咨询
POST {{apiUrl}}/api/v1/node/consult
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

{
  "data": {
    "type": "node--consult",
    "attributes": {
      "title": "new consult by Johnson status false",
      "status":false,
      "body": {
        "value": "Hello world! Lorem ipsum dolor sit amet consectetur adipiscing elit",
        "format": "plain_text"
      }
    },
    "relationships":{
      "field_tags":{
        "data":{
              "type": "taxonomy_term--consult_type",
              "id": "9af0acac-db7a-42ef-b4a6-cc19313d89a9"
            }
      }
    }
  }
}
