### https://www.drupal.org/docs/8/core/modules/rest/javascript-and-drupal-8-restful-web-services#s-login
@apiUrl = https://lxyadmin.zhaobg.com
@user = test
@psw = test
@user_uuid = d5fb03cb-abca-43ba-baa5-a162a576e67a
@node_uuid = 97edbdba-16a9-4e48-9285-9a2854968cf7

### user login
# @name login
POST {{apiUrl}}/user/login?_format=json HTTP/1.1
content-type: application/json

{"name": "{{user}}","pass": "{{psw}}"}

###

@logoutToken = {{login.response.body.logout_token}}

###

@csrfToken = {{login.response.body.csrf_token}}

### get user status
GET {{apiUrl}}/user/login_status?_format=json HTTP/1.1

### user logout
POST {{apiUrl}}/user/logout?_format=json&token={{logoutToken}} HTTP/1.1
Content-type: application/json
withCredentials: true
### logout v2 强制退出
POST {{apiUrl}}/user/logout HTTP/1.1

### get user uuid
GET {{apiUrl}}/api/v1/user/user?filter[drupal_internal__uid]={{login.response.body.current_user.uid}}

### get user
GET {{apiUrl}}/api/v1/user/user?filter[drupal_internal__uid]={{login.response.body.current_user.uid}}&include=user_picture

### get all api
GET {{apiUrl}}/api/v1

### get all user
GET {{apiUrl}}/api/v1/user/user

### https://www.drupal.org/docs/core-modules-and-themes/core-modules/api/v1-module/api-overview
### https://explore.api/v1.dev/


### taxonomy
GET {{apiUrl}}/api/v1/node/recruitment/5c67b19c-b8c4-495b-8a6f-1bea1a852a49/skill?resourceVersion=id%3A90

### taxonomy skill
GET {{apiUrl}}/api/v1/taxonomy_term/skill

### https://dev.acquia.com/blog/decoupling-drupal-8-with-json-api/15/05/2018/19596

@type=case

### get need set header Accept: application/vnd.api+json

### get single resource
GET {{apiUrl}}/api/v1/node/{{type}}/675aea30-2e32-4d5c-a52a-08a79009e43f
### get collections rsource
GET {{apiUrl}}/api/v1/node/{{type}}

### get collections limit
GET {{apiUrl}}/api/v1/node/{{type}}?page[limit]=10

### get collections offset
GET {{apiUrl}}//api/v1/node/{{type}}?page[limit]=25&page[offset]=25

### sort by title or -title
GET {{apiUrl}}/api/v1/node/{{type}}?sort=title

### sort by nid or -nid
{{apiUrl}}/api/v1/node/{{type}}?sort=nid

### get case fields what you want
GET {{apiUrl}}/api/v1/node/{{type}}?fields[node--{{type}}]=title,field_image,field_tags&include=field_image,field_tags&fields[file--file]=uri&fields[taxonomy_term--industry]=name
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

### get job fields what you want
GET {{apiUrl}}/api/v1/node/{{type}}?fields[node--{{type}}]=title,created,changed,body,deadline,number,salary,work_experience,skill,education,company&include=skill,education,company,company.logo&fields[taxonomy_term--skill]=name&fields[taxonomy_term--education]=name&fields[node--company]=title,address,phone,welfare,logo&fields[file--file]=uri
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

### all post, patch, delete need set header
### Accept: application/vnd.api+json
### Content-Type: application/vnd.api+json
### 'X-CSRF-Token'
### 需要注意字段必须包含所有的必填项

@sample_type = question
@article_node_uuid = bb0617db-af29-4239-b824-4131f29d7530

### creating node
POST {{apiUrl}}/api/v1/node/{{sample_type}} HTTP/1.1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

{
  "data": {
    "type": "node--{{sample_type}}",
    "attributes": {
      "title": "new article by Johnson",
      "body": {
        "value": "Hello world! Lorem ipsum dolor sit amet consectetur adipiscing elit",
        "format": "plain_text"
      }
    },
    "relationships": {
      "uid": {
        "data": {
          "type": "user--user",
          "id": "{{user_uuid}}"
        }
      }
    }
  }
}

### update single node
PATCH {{apiUrl}}/api/v1/node/article/{{article_node_uuid}}
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

{
  "data": {
    "type": "node--article",
    "id": "{{article_node_uuid}}",
    "attributes": {
      "title": "update the article",
    },
    "relationships": {
      "uid": {
        "data": {
          "type": "user--user",
          "id": "{{user_uuid}}"
        }
      }
    }
  }
}


### delete single node
DELETE {{apiUrl}}/api/v1/node/article/{{article_node_uuid}}
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}


### post question comment
POST {{apiUrl}}/api/v1/comment/answer
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
X-CSRF-Token: {{csrfToken}}

{
  "data":{
    "type":"comment--answer",
    "attributes":{
      "entity_type":"node",
      "field_name":"answer",
      "content":{
        "value":"New comment by johnson!",
        "format":"plain_text"
      }
    },
    "relationships":{
      "comment_type":{
        "data":{
          "type":"comment_type--comment_type",
          "id":"a395ac8e-3c9a-43d5-8ec8-cea74116d5f3"
        }
      },
      "entity_id":{
        "data":{
          "type":"node--question",
          "id":"18dac740-1d11-43c0-a431-d2b9e402fe6b"
        }
      }
    }
  }
}
