import {
  moduleMetadata,
  Meta,
  StoryObj,
  applicationConfig,
} from '@storybook/angular';

import { StorysModule } from '@core/module/storys.module';
import { IS_BUILDER_MODE } from '@core/token/token-providers';
import { of } from 'rxjs';
import { LayoutBuilderComponent } from '@modules/builder/layout-builder/layout-builder.component';
import { importProvidersFrom } from '@angular/core';
import { SafeHtmlPipe } from '@core/pipe/safe-html.pipe';
import { ReqRolesDirective } from '@core/directive/req-roles.directive';
const meta: Meta<LayoutBuilderComponent> = {
  title: '低代码/Layout builder/示例',
  id: 'layoutBuilder',
  component: LayoutBuilderComponent,
  decorators: [
    applicationConfig({
      providers: [importProvidersFrom(StorysModule.forRoot())],
    }),
    moduleMetadata({
      declarations: [
        ...StorysModule.forEntryComponents(),
        SafeHtmlPipe,
        ReqRolesDirective,
      ],
      providers: [
        {
          provide: IS_BUILDER_MODE,
          useValue: of(false),
        },
      ],
    }),
  ],
  parameters: {
    layout: 'fullscreen',
  },
};

export default meta;
type Story = StoryObj<LayoutBuilderComponent>;

export const LayoutDefault: Story = {};
LayoutDefault.storyName = '默认';
LayoutDefault.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'md',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '/assets/images/bg/home-shape.png',
        classes: 'object-fit',
        alt: 'home-shape.png',
      },
      classes: 'bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'center',
    animate: {
      from: {
        x: 0,
        y: 0,
        rotation: 0,
        scale: 1,
        opacity: 1,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        row: {
          xs: 12,
          sm: 6,
          md: 6,
          lg: 7,
        },
        horizontal: 'center',
        vertical: 'start',
        gap: {
          xs: '2',
          sm: '2',
          md: '2',
          lg: '2',
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        style: {
          borderRadius: 'none',
          padding: '',
          margin: '',
        },
        animate: {
          from: {
            x: 0,
            y: '100',
            rotation: 0,
            scale: 1,
            opacity: 0,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            type: 'title',
            label:
              '欢迎使用 <strong class="text-primary">Web Builder</strong> 快速构建响应式页面',
            style: 'style-v4',
            classes: 'mat-display-1 bold',
          },
          {
            type: 'text',
            spacer: 'none',
            body: '信使UI是基于 Material 的 Angular 前端框架， 五十多个丰富的组件可提供优秀的数字创新体验，使用 Web Builder 可以通过拖拽快速构建响应式、多主题的 Web 页面。Builder 与众不同的是它完全融入到了 <strong class="text-primary">Storybook</strong> 当中，它是一个面向UI组件开发的工具，提供了组件驱动的开发方式、交互式展示和测试界面，以及文档化功能。',
            bg: {
              classes: 'bg- bg-fill-width',
            },
            classes: '',
          },
          {
            type: 'card-1v4',
            img: {
              classes: 'object-fit',
              src: '/assets/images/avatar/01.jpeg',
            },
            star: 5,
            title: '- Johnson',
            subTitle: '前端开发',
            body: '信使是一个灵活可扩展性高的前端Anuglar框架，动态组件可以使得组件之间变得更加灵活，但是依赖循环也变得复杂。',
          },
          {
            type: 'btn',
            href: '/node/1',
            target: '_blank',
            label: '了解更多',
            mode: 'raised',
            color: 'primary',
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 6,
          md: 6,
          lg: 5,
        },
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        style: {
          borderRadius: 'none',
        },
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        horizontal: 'center',
        vertical: 'center',
        elements: [
          {
            classes: '',
            alt: 'alt',
            hostClasses: 'text-center',
            animate: {
              from: {
                x: '100',
                y: 0,
                rotation: 0,
                scale: 0.8,
                opacity: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
                scrub: false,
              },
            },
            type: 'img',
            src: '/assets/images/illustration/11.png',
            style: {
              'max-width': '60%',
            },
          },
        ],
      },
    ],
  },
};

export const TwoCol: Story = {};
TwoCol.storyName = '两栏';
TwoCol.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'md',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '',
        classes: 'object-fit',
        alt: '',
      },
      classes: 'bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'stretch',
    gap: {
      xs: '5',
    },
    wrapperClass: 'sm:flex-nowrap',
    animate: {
      from: {
        x: 0,
        y: '100',
        rotation: 0,
        scale: 1,
        opacity: 0,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        row: {
          xs: 12,
          sm: 6,
          md: 6,
          lg: 6,
        },
        horizontal: 'center',
        vertical: 'center',
        gap: {
          xs: '10',
          sm: '10',
          md: '10',
          lg: '10',
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg- bg-fill-width',
        },
        classes: '',
        blockClasses: 'bg-shadow ',
        style: {
          borderRadius: 'none',
          margin: '',
        },
        animate: {
          from: {
            x: 0,
            y: '0',
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            style: 'none',
            classes: 'mat-display-1 bold',
            typed: {
              enable: false,
              config: {
                typeSpeed: 120,
              },
              strings: [
                {
                  label: 'web builder',
                },
              ],
            },
            animate: {
              from: {
                x: 0,
                y: 0,
                rotation: 0,
                scale: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
              },
            },
            type: 'title',
            label: '自由搭配，玩出新意',
          },
          {
            type: 'link',
            label: '链接搭配你的风格',
            classes: '',
            href: '/',
          },
          {
            src: '/assets/images/products/huawei-watch-gt4-select-strap.webp',
            classes: '',
            alt: 'alt',
            style: {
              width: '450px',
              height: '300px',
              opacity: '1',
              borderRadius: '0px',
              boxShadow: 'none',
              aspectRatio: '1 / 1',
              objectFit: 'contain',
            },
            hostClasses: 'text-center',
            animate: {
              from: {
                x: '0',
                y: 0,
                rotation: 0,
                scale: 1,
                opacity: 0,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
                scrub: true,
              },
            },
            type: 'img',
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 6,
          md: 6,
          lg: 6,
        },
        horizontal: 'center',
        vertical: 'center',
        gap: {
          xs: '10',
          sm: '10',
          md: '10',
          lg: '10',
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg- bg-fill-width',
        },
        classes: '',
        blockClasses: 'bg-shadow',
        style: {
          borderRadius: 'none',
          margin: '',
        },
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            style: 'none',
            classes: 'mat-display-1 bold',
            typed: {
              enable: false,
              config: {
                typeSpeed: 120,
              },
              strings: [
                {
                  label: 'web builder',
                },
              ],
            },
            animate: {
              from: {
                x: 0,
                y: 0,
                rotation: 0,
                scale: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
              },
            },
            type: 'title',
            label: '款款亮眼，爱不释手',
          },
          {
            type: 'link',
            label: '探索更多',
            classes: '',
            href: '/',
          },
          {
            src: '/assets/images/products/huawei-watch-gt4-Huawei-wearables.webp',
            classes: '',
            alt: 'alt',
            style: {
              width: '450px',
              height: '300px',
              opacity: '1',
              borderRadius: '0px',
              boxShadow: 'none',
              aspectRatio: '1 / 1',
              objectFit: 'contain',
            },
            hostClasses: 'text-center',
            animate: {
              from: {
                x: '0',
                y: 0,
                rotation: 0,
                scale: 1,
                opacity: 0,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
                scrub: true,
              },
            },
            type: 'img',
          },
        ],
      },
    ],
  },
};

export const ThreeCol: Story = {};
ThreeCol.storyName = '三栏';
ThreeCol.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'md',
    bgClasses: 'bg-shadow bg-fill-width',
    overlay: '',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '/assets/images/bg/home-shape.png',
        classes: 'object-fit',
        alt: 'home-shape.png',
      },
      classes: 'bg-shadow bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'center',
    animate: {
      from: {
        x: 0,
        y: 0,
        rotation: 0,
        scale: 1,
        opacity: 1,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        row: {
          xs: 12,
          sm: 4,
          md: 4,
          lg: 4,
        },
        horizontal: 'center',
        vertical: 'stretch',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        animate: {
          from: {
            x: 0,
            y: '100',
            rotation: 0,
            scale: 1,
            opacity: 0,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            type: 'box',
            img: {
              src: '/assets/images/svg/Asset187.svg',
              alt: 'browser',
            },
            style: 'style-v3 use-image',
            title: {
              href: '#',
              label: '高性能',
            },
            content:
              '默认情况下，Drupal 运行速度很快，您可以优化部署，使其运行得更快；',
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 4,
          md: 4,
          lg: 4,
        },
        horizontal: 'center',
        vertical: 'stretch',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        animate: {
          from: {
            x: 0,
            y: '100',
            rotation: 0,
            scale: 1,
            opacity: 0,
            delay: '0.6',
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            type: 'box',
            img: {
              src: '/assets/images/svg/Asset189.svg',
              alt: 'browser',
            },
            style: 'style-v3 use-image primary',
            title: {
              href: '#',
              label: '易用的编辑器',
            },
            content:
              '通过友好的预览、拖放媒体提高内容编辑的易用性，高效的工作；',
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 4,
          md: 4,
          lg: 4,
        },
        horizontal: 'center',
        vertical: 'center',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        blockClasses: '',
        animate: {
          from: {
            x: 0,
            y: '100',
            rotation: 0,
            scale: 1,
            opacity: '0',
            delay: '1',
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        elements: [
          {
            type: 'box',
            img: {
              src: '/assets/images/svg/Asset190.svg',
              alt: 'browser',
            },
            style: 'style-v3 use-image',
            title: {
              href: '#',
              label: '多语言',
            },
            content: 'Drupal 100多种语言提供了无以伦比的支持和翻译工作流程； ',
          },
        ],
      },
    ],
  },
};

export const FourCol: Story = {};
FourCol.storyName = '四栏';
FourCol.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'md',
    bgClasses: 'bg-shadow bg-fill-width',
    overlay: '',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '/assets/images/bg/home-shape.png',
        classes: 'object-fit',
        alt: 'home-shape.png',
      },
      classes: 'bg-shadow bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'center',
    animate: {
      from: {
        x: 0,
        y: 0,
        rotation: 0,
        scale: 1,
        opacity: 1,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        row: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        horizontal: 'end',
        vertical: 'end',
        gap: {
          xs: '10',
          sm: '10',
          md: '10',
          lg: '10',
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        style: {
          borderRadius: 'none',
          padding: '',
          margin: '',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        animate: {
          from: {
            x: 0,
            y: '100',
            rotation: 0,
            scale: 1,
            opacity: '0',
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },

        elements: [
          {
            spacer: 'none',
            body: '<p style="display: inline-block; margin-bottom: 0px;">把想法转化给设计稿，根据设计稿通过拖拽出响应式页面，大大降低开发成本，将注意力放在您的业务。</p>',
            animate: {
              from: {
                x: 0,
                y: 0,
                rotation: 0,
                scale: 1,
                opacity: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
              },
            },
            type: 'text',
          },
          {
            src: 'https://www2.bettyblocks.com/hubfs/RH-images/striped-arrow.svg',
            classes: 'm-bottom-md',
            alt: 'alt',
            style: {
              aspectRatio: 'auto',
              objectFit: 'initial',
            },
            hostClasses: 'text-center',
            animate: {
              from: {
                x: 0,
                y: 0,
                rotation: 0,
                scale: 1,
                opacity: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
              },
            },
            type: 'img',
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        horizontal: 'center',
        vertical: 'stretch',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        blockClasses: 'p-5',
        style: {
          borderRadius: 'none',
          padding: '20px',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        animate: {
          from: {
            x: 0,
            y: '100',
            rotation: 0,
            scale: 1,
            opacity: '0',
            delay: '0.6',
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            type: 'card-1v1',
            link: {
              href: '/node/463',
              label: '信使 UI 应用初始化及页面渲染流程',
            },
            user: '表歌',
            time: '2022/09/27',
            feature: {
              fullIcon: 'fullscreen',
              openIcon: 'open_in_new',
              link: '#',
              ratios: 'media-4-3',
              img: {
                classes: 'object-fit',
                src: '/assets/images/hero/bg01.jpg',
                alt: 'alt',
                style: {
                  width: 'auto',
                  height: 'auto',
                  opacity: '1',
                  borderRadius: 0,
                  boxShadow: 'none',
                  aspectRatio: 'auto',
                  objectFit: 'initial',
                },
              },
            },
            moreLabel: '查看更多',
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        horizontal: 'center',
        vertical: 'stretch',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        blockClasses: 'p-5',
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        animate: {
          from: {
            x: 0,
            y: '100',
            rotation: 0,
            scale: 1,
            opacity: '0',
            delay: '1.2',
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            type: 'card-1v1',
            link: {
              href: '/node/462',
              label: '信使Web builder 新增自定义组件流程',
            },
            user: '表歌',
            time: '2022/09/27',
            feature: {
              fullIcon: 'fullscreen',
              openIcon: 'open_in_new',
              link: '#',
              ratios: 'media-4-3',
              img: {
                classes: 'object-fit',
                src: '/assets/images/hero/bg02.jpg',
                alt: 'alt',
                style: {
                  width: 'auto',
                  height: 'auto',
                  opacity: '1',
                  borderRadius: 0,
                  boxShadow: 'none',
                  aspectRatio: 'auto',
                  objectFit: 'initial',
                },
              },
            },
            moreLabel: '查看更多',
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        horizontal: 'center',
        vertical: 'stretch',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        blockClasses: 'p-5',
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        animate: {
          from: {
            x: 0,
            y: '100',
            rotation: 0,
            scale: 1,
            opacity: '0',
            delay: '1.2',
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            type: 'card-1v1',
            link: {
              href: '/node/450',
              label: '作为前端开发，你应该知道的这十几个在线免费工具',
            },
            user: '表歌',
            time: '2022/09/27',
            feature: {
              fullIcon: 'fullscreen',
              openIcon: 'open_in_new',
              link: '#',
              ratios: 'media-4-3',
              img: {
                classes: 'object-fit',
                src: '/assets/images/hero/bg05.jpg',
                alt: 'alt',
                style: {
                  width: 'auto',
                  height: 'auto',
                  opacity: '1',
                  borderRadius: 0,
                  boxShadow: 'none',
                  aspectRatio: 'auto',
                  objectFit: 'initial',
                },
              },
            },
            moreLabel: '查看更多',
          },
        ],
      },
    ],
  },
};

export const Section1A: Story = {};
Section1A.storyName = '1A';
Section1A.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'xl',
    bgClasses: 'bg-shadow bg-fill-width',
    overlay: '',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '/assets/images/bg/bg-02.png',
        classes: 'object-fit',
        alt: 'bg-02',
      },
      classes: 'bg-shadow bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'center',
    animate: {
      from: {
        x: 0,
        y: 0,
        rotation: 0,
        scale: 1,
        opacity: 1,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        row: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 6,
        },
        horizontal: 'start',
        vertical: 'stretch',
        gap: {
          xs: '4',
          sm: '4',
          md: '4',
          lg: '4',
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        style: {
          borderRadius: 'none',
        },
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },

        elements: [
          {
            style: 'style-v4',
            classes: 'mat-display-1 bold',
            typed: {
              enable: false,
              config: {
                typeSpeed: 120,
              },
              strings: [
                {
                  label: 'web builder',
                },
              ],
            },
            animate: {
              from: {
                x: 0,
                y: 0,
                rotation: 0,
                scale: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
              },
            },
            type: 'title',
            label:
              '欢迎使用 <strong class="text-primary">Web Builder</strong> 快速构建响应式页面',
          },
          {
            type: 'text',
            spacer: 'none',
            body: '信使UI是基于 Material 的 Angular 前端框架，丰富的组件可提供优秀的数字创新体验，使用 Web Builder 可以通过拖拽快速构建响应式、多主题的 Web 页面。',
          },
          {
            type: 'btn',
            href: '/node/1',
            target: '_blank',
            label: '了解更多',
            mode: 'raised',
            color: 'primary',
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 6,
        },
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        horizontal: 'start',
        vertical: 'stretch',
        classes: '',
        style: {
          borderRadius: 'none',
        },
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },

        elements: [
          {
            type: 'spacer',
            size: 'sm',
          },
          {
            type: 'img',
            hostClasses: 'text-center',
            classes: '',
            src: '/assets/images/illustration/08.png',
            alt: 'alt',
            style: {
              width: 'auto',
              height: 'auto',
              opacity: 1,
              borderRadius: 0,
              boxShadow: 'none',
              aspectRatio: '2 / 1',
              objectFit: 'contain',
            },
          },
          {
            type: 'spacer',
            size: 'sm',
          },
        ],
      },
    ],
  },
};

export const Section1B: Story = {};
Section1B.storyName = '1B';
Section1B.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'xl',
    bgClasses: 'bg-shadow bg-fill-width',
    overlay: '',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '/assets/images/bg/home-shape.png',
        classes: 'object-fit',
        alt: 'home-shape',
      },
      classes: 'bg-shadow bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'center',
    gap: {
      xs: '5',
    },
    animate: {
      from: {
        x: 0,
        y: 0,
        rotation: 0,
        scale: 1,
        opacity: 1,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        row: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 6,
        },
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        style: {
          borderRadius: 'none',
        },
        horizontal: 'start',
        vertical: 'stretch',
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },

        elements: [
          {
            type: 'spacer',
            size: 'sm',
          },
          {
            type: 'img',
            hostClasses: 'text-center',
            classes: '',
            src: '/assets/images/illustration/08.png',
            alt: 'alt',
            style: {
              width: 'auto',
              height: 'auto',
              opacity: 1,
              borderRadius: 0,
              boxShadow: 'none',
              aspectRatio: '2 / 1',
              objectFit: 'contain',
            },
          },
          {
            type: 'spacer',
            size: 'sm',
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 6,
        },
        gap: {
          xs: '4',
          sm: '4',
          md: '4',
          lg: '4',
        },
        horizontal: 'start',
        vertical: 'stretch',
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        style: {
          borderRadius: 'none',
        },
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },

        elements: [
          {
            style: 'style-v4',
            classes: 'mat-display-1 bold',
            typed: {
              enable: false,
              config: {
                typeSpeed: 120,
              },
              strings: [
                {
                  label: 'web builder',
                },
              ],
            },
            animate: {
              from: {
                x: 0,
                y: 0,
                rotation: 0,
                scale: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
              },
            },
            type: 'title',
            label:
              '欢迎使用 <strong class="text-primary">Web Builder</strong> 快速构建响应式页面',
          },
          {
            type: 'text',
            spacer: 'none',
            body: '信使UI是基于 Material 的 Angular 前端框架，丰富的组件可提供优秀的数字创新体验，使用 Web Builder 可以通过拖拽快速构建响应式、多主题的 Web 页面。',
          },
          {
            type: 'btn',
            href: '/node/1',
            target: '_blank',
            label: '了解更多',
            mode: 'raised',
            color: 'primary',
          },
        ],
      },
    ],
  },
};

export const Section2A: Story = {};
Section2A.storyName = '2A';
Section2A.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'md',
    bgClasses: 'bg-fill-width',
    overlay: '',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '/assets/images/bg/bg-01.png',
        classes: 'object-fit',
        alt: 'bg-01.png',
      },
      classes: 'bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'center',
    animate: {
      from: {
        x: 0,
        y: 0,
        rotation: 0,
        scale: 1,
        opacity: 1,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        row: {
          xs: 12,
          sm: 12,
          md: 12,
          lg: 12,
        },
        horizontal: 'center',
        vertical: 'center',
        gap: {
          xs: '10',
          sm: '10',
          md: '10',
          lg: '20',
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        blockClasses: '',
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            type: 'img',
            hostClasses: 'text-center',
            classes: '',
            src: 'http://localhost:4200/assets/images/illustration/09.png',
            alt: 'alt',
            style: {
              width: 'auto',
              height: 'auto',
              opacity: '1',
              borderRadius: '0px',
              boxShadow: 'none',
              aspectRatio: 'auto',
              objectFit: 'initial',
            },
          },
          {
            style: 'style-v1',
            classes: 'mat-display-1 bold',
            typed: {
              enable: false,
              config: {
                typeSpeed: 120,
              },
              strings: [
                {
                  label: 'web builder',
                },
              ],
            },
            animate: {
              from: {
                x: 0,
                y: 0,
                rotation: 0,
                scale: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
              },
            },
            type: 'title',
            label:
              '欢迎使用 <strong class="text-primary">Web Builder</strong> 快速构建响应式页面',
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 12,
          md: 12,
          lg: 12,
        },
        horizontal: 'center',
        vertical: 'center',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        blockClasses: '',
        style: {
          borderRadius: 'none',
        },
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            spacer: 'none',
            classes: 'md:max-w-3/4 mx-auto',
            body: '<p class="ql-align-center">信使UI是基于 Material 的 Angular 前端框架， 丰富的组件可提供优秀的数字创新体验，使用 Web Builder 可以通过拖拽快速构建响应式、多主题的 Web 页面。基于Angular Material UI，支持SSR，多应用，后端可根据实际情况自由配置，可自定义开发、新增组件库。</p>',
            animate: {
              from: {
                x: 0,
                y: 0,
                rotation: 0,
                scale: 1,
                opacity: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
              },
            },
            type: 'text',
          },
        ],
      },
      {
        classes: '',
        row: {
          xs: 12,
          sm: 12,
          md: 12,
          lg: 12,
        },
        horizontal: 'center',
        vertical: 'center',
        elements: [
          {
            type: 'btn',
            href: '/node/1',
            target: '_blank',
            label: '了解更多',
            mode: 'raised',
            color: 'primary',
          },
        ],
      },
    ],
  },
};

export const Section2B: Story = {};
Section2B.storyName = '2B';
Section2B.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'md',
    bgClasses: 'bg-fill-width',
    overlay: '',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '/assets/images/bg/bg-01.png',
        classes: 'object-fit',
        alt: 'bg-01.png',
      },
      classes: 'bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'center',
    animate: {
      from: {
        x: 0,
        y: 0,
        rotation: 0,
        scale: 1,
        opacity: 1,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        classes: '',
        row: {
          xs: 12,
          sm: 12,
          md: 12,
          lg: 12,
        },
        horizontal: 'start',
        vertical: 'stretch',
        elements: [
          {
            type: 'title',
            label:
              '欢迎使用 <strong class="text-primary">Web Builder</strong> 快速构建响应式页面',
            style: 'style-v1',
            classes: 'mat-display-1 bold',
          },
        ],
      },
      {
        classes: '',
        row: {
          xs: 12,
          sm: 12,
          md: 12,
          lg: 12,
        },
        horizontal: 'start',
        vertical: 'stretch',
        elements: [
          {
            type: 'text',
            spacer: 'none',
            classes: 'md:max-w-3/4 mx-auto',
            body: '<p class="ql-align-center">信使UI是基于 Material 的 Angular 前端框架， 丰富的组件可提供优秀的数字创新体验，使用 Web Builder 可以通过拖拽快速构建响应式、多主题的 Web 页面。基于Angular Material UI，支持SSR，多应用，后端可根据实际情况自由配置，可自定义开发、新增组件库。</p>',
          },
        ],
      },
      {
        classes: '',
        row: {
          xs: 12,
          sm: 12,
          md: 12,
          lg: 12,
        },
        horizontal: 'start',
        vertical: 'stretch',
        elements: [
          {
            type: 'btn',
            href: '/node/1',
            target: '_blank',
            label: '了解更多',
            mode: 'raised',
            color: 'primary',
          },
        ],
      },
      {
        classes: '',
        row: {
          xs: 12,
          sm: 12,
          md: 12,
          lg: 12,
        },
        horizontal: 'start',
        vertical: 'stretch',
        elements: [
          {
            src: '/assets/images/builder/builder-01.png',
            classes: 'mt-5',
            hostClasses: 'text-center',
            alt: 'alt',
            style: {
              width: '85%',
              height: 'auto',
              opacity: '0.9',
              borderRadius: '14px',
              boxShadow: 'rgba(0, 0, 0, 0.1) 0px 4px 8px',
              aspectRatio: 'auto',
              objectFit: 'contain',
            },
            animate: {
              from: {
                x: 0,
                y: '300',
                rotation: 0,
                scale: '1',
                opacity: 0,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
                scrub: true,
              },
            },
            type: 'img',
          },
        ],
      },
    ],
  },
};

export const Section3A: Story = {};
Section3A.storyName = '3A';
Section3A.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'md',
    bgClasses: 'bg-shadow bg-fill-width',
    overlay: '',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '',
        classes: 'object-fit',
        alt: '',
      },
      classes: 'bg-shadow bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'center',
    gap: {
      xs: 0,
      sm: 4,
    },
    animate: {
      from: {
        x: 0,
        y: 0,
        rotation: 0,
        scale: 1,
        opacity: 1,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        row: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 6,
        },

        horizontal: 'start',
        vertical: 'stretch',
        gap: {
          xs: '4',
          sm: '4',
          md: '4',
          lg: '4',
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: 'mb-5',
        blockClasses: '',
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            type: 'title',
            label:
              '欢迎使用 <strong class="text-primary">Web Builder</strong> 快速构建响应式页面',
            style: 'style-v4',
            classes: 'mat-display-1 bold',
          },
          {
            type: 'text',
            spacer: 'none',
            body: '信使UI是基于 Material 的 Angular 前端框架，丰富的组件可提供优秀的数字创新体验，使用 Web Builder 可以通过拖拽快速构建响应式、多主题的 Web 页面。',
          },
          {
            type: 'btn',
            href: '/node/1',
            target: '_blank',
            label: '了解更多',
            mode: 'raised',
            color: 'primary',
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 6,
        },
        horizontal: 'start',
        vertical: 'start',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: 'overflow-hidden',
        blockClasses: '',
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        style: {
          borderRadius: 'none',
        },
        elements: [
          {
            params: {
              direction: 'horizontal',
              breakpoints: {
                '600': {
                  slidesPerView: 3,
                  spaceBetween: 20,
                },
                '960': {
                  slidesPerView: 3,
                  spaceBetween: '20',
                },
              },
              effect: 'slide',
              speed: 300,
              pagination: {
                paginationEnable: false,
              },
              navigation: false,
              centeredSlides: false,
              loop: false,
              autoplay: false,
              mousewheel: false,
            },
            animate: {
              from: {
                x: 0,
                y: 0,
                rotation: 0,
                scale: 1,
                opacity: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
              },
            },
            type: 'swiper',
            classes: '',
            elements: [
              {
                type: 'card',
                title: '高性能',
                subTitle: 'High Performance',
                classes: 'card-no-shadow',
                body: '默认情况下，Drupal 运行速度很快，您可以优化部署，使其运行得更快；',
                feature: {
                  fullIcon: 'fullscreen',
                  openIcon: 'open_in_new',
                  link: '#',
                  ratios: 'media-4-3',
                  img: {
                    classes: 'object-fit',
                    src: '/assets/images/cases/porto1.jpg',
                    alt: 'alt',
                  },
                },
              },
              {
                type: 'card',
                feature: {
                  fullIcon: 'fullscreen',
                  openIcon: 'open_in_new',
                  link: '#',
                  ratios: 'media-4-3',
                  img: {
                    classes: 'object-fit',
                    src: '/assets/images/cases/porto7.jpg',
                    alt: 'alt',
                  },
                },
                title: '易用的编辑器',
                subTitle: 'Simplicity for Editors',
                classes: 'card-no-shadow',
                body: '通过友好的预览、拖放媒体提高内容编辑的易用性，高效的工作；',
              },
              {
                type: 'card',
                feature: {
                  fullIcon: 'fullscreen',
                  openIcon: 'open_in_new',
                  link: '#',
                  ratios: 'media-4-3',
                  img: {
                    classes: 'object-fit',
                    src: '/assets/images/cases/porto2.jpg',
                    alt: 'alt',
                  },
                },
                title: '多语言',
                subTitle: 'Leader in Multilingual',
                classes: 'card-no-shadow',
                body: 'Drupal 100多种语言提供了无以伦比的支持和翻译工作流程；',
              },
              {
                type: 'card',
                feature: {
                  fullIcon: 'fullscreen',
                  openIcon: 'open_in_new',
                  link: '#',
                  ratios: 'media-4-3',
                  img: {
                    classes: 'object-fit',
                    src: '/assets/images/cases/porto3.jpg',
                    alt: 'alt',
                  },
                },
                title: '更有弹性',
                subTitle: 'Flexibility',
                classes: 'card-no-shadow',
                body: '无论是一个还是多个站点，Drupal 总是可以游刃有余的构建；',
              },
              {
                type: 'card',
                feature: {
                  fullIcon: 'fullscreen',
                  openIcon: 'open_in_new',
                  link: '#',
                  ratios: 'media-4-3',
                  img: {
                    classes: 'object-fit',
                    src: '/assets/images/cases/porto4.jpg',
                    alt: 'alt',
                  },
                },
                title: '安全性',
                subTitle: 'Rigorous Security',
                classes: 'card-no-shadow',
                body: '为了抵御安全漏洞，将有一组团队解决并发布安全修补程序，超过45000名贡献者使该平台成为市场上最安全、最稳定的平台之一；',
              },
            ],
          },
        ],
      },
    ],
  },
};

export const Section3B: Story = {};
Section3B.storyName = '3B';
Section3B.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'md',
    bgClasses: 'bg-shadow bg-fill-width',
    overlay: '',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '/assets/images/bg/home-shape.png',
        classes: 'object-fit',
        alt: 'home-shape.png',
      },
      classes: 'bg-shadow bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'center',
    gap: {
      xs: 0,
    },
    animate: {
      from: {
        x: 0,
        y: 0,
        rotation: 0,
        scale: 1,
        opacity: 1,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        row: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        horizontal: 'center',
        vertical: 'stretch',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: 'mb-5',
        blockClasses: '',
        animate: {
          from: {
            x: 0,
            y: '100',
            rotation: 0,
            scale: 1,
            opacity: '0',
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        elements: [
          {
            title: {
              label: '免费',
              classes: '',
            },
            type: 'card-1v6',
            prefix: '¥',
            number: '0',
            suffix: '/月',
            body: '<ul class="list-done"><li>获得免费访问平台的权限</li><li>浏览平台上公开的内容和资源</li><li>参与在线社区讨论和互动</li></ul>',
            actionsAlign: 'start center',
            actions: [
              {
                type: 'btn',
                href: '/node/1',
                target: '_blank',
                label: '立即注册',
                mode: 'raised',
                color: 'primary',
              },
            ],
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        horizontal: 'center',
        vertical: 'stretch',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: 'mb-5',
        blockClasses: '',
        animate: {
          from: {
            x: 0,
            y: '200',
            rotation: 0,
            scale: 1,
            opacity: '0',
            delay: '0.6',
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
            scrub: true,
          },
        },
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        elements: [
          {
            title: {
              label: '初级会员',
              classes: 'text-primary',
            },
            type: 'card-1v6',
            prefix: '¥',
            number: '99',
            suffix: '/月',
            classes: 'bg-light',
            body: '<ul class="list-done"><li>所有免费会员功能</li><li>享受高质量、独家的内容和教程</li><li>获得快速响应的客户支持服务</li><li>参与平台举办的活动和专属优惠</li></ul>',
            actionsAlign: 'start center',
            actions: [
              {
                type: 'btn',
                href: '/node/1',
                target: '_blank',
                label: '立即购买',
                mode: 'raised',
                color: 'primary',
              },
            ],
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        horizontal: 'center',
        vertical: 'stretch',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: 'mb-5',
        blockClasses: '',
        animate: {
          from: {
            x: 0,
            y: '100',
            rotation: 0,
            scale: 1,
            opacity: '0',
            delay: '0.6',
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        elements: [
          {
            title: {
              label: '高级会员',
              classes: '',
            },
            type: 'card-1v6',
            prefix: '¥',
            number: '899',
            suffix: '/月',
            body: '<ul class="list-done"><li>所有初级会员功能</li><li>获取深入的教程和指导</li><li>允许下载平台上的资源和素材</li><li>获得个性化的设计建议和反馈</li></ul>',
            actionsAlign: 'start center',
            actions: [
              {
                type: 'btn',
                href: '/node/1',
                target: '_blank',
                label: '立即购买',
                mode: 'raised',
                color: 'primary',
              },
            ],
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        horizontal: 'center',
        vertical: 'stretch',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: 'mb-5',
        blockClasses: '',
        animate: {
          from: {
            x: 0,
            y: '100',
            rotation: 0,
            scale: 1,
            opacity: '0',
            delay: '1.2',
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        elements: [
          {
            title: {
              label: '白金会员',
              classes: '',
            },
            type: 'card-1v6',
            prefix: '¥',
            number: '2889',
            suffix: '/月',
            body: '<ul class="list-done"><li>所有高级会员功能</li><li>使用平台提供的高级设计工具和插件</li><li>参与专业会员专属的培训和活动</li><li>与专业设计师一对一的指导</li></ul>',
            actionsAlign: 'start center',
            actions: [
              {
                type: 'btn',
                href: '/node/1',
                target: '_blank',
                label: '立即购买',
                mode: 'raised',
                color: 'primary',
              },
            ],
          },
        ],
      },
    ],
  },
};

export const Section4A: Story = {};
Section4A.storyName = '4A';
Section4A.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'md',
    bgClasses: 'bg- bg-fill-width',
    overlay: '',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '/assets/images/bg/bg-02.png',
        alt: 'bg-02',
        classes: 'object-fit',
      },
      classes: 'bg- bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'center',
    gap: {
      xs: '5',
    },
    wrapperClass: '',
    alignItems: 'center',
    animate: {
      from: {
        x: 0,
        y: 0,
        rotation: 0,
        scale: 1,
        opacity: 1,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        row: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 7,
        },
        horizontal: 'start',
        vertical: 'start',
        gap: {
          xs: '4',
          sm: '4',
          md: '4',
          lg: '4',
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        blockClasses: '',
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        elements: [
          {
            horizontal: 'center',
            vertical: 'center',
            gap: {
              xs: '4',
              sm: '4',
              md: '5',
              lg: '5',
            },
            wrapperClass: '',
            spacer: 'md',
            row: {
              xs: 12,
              sm: 12,
              md: 12,
              lg: 12,
            },
            bg: {
              img: {
                src: '',
                alt: '',
                classes: 'object-fit',
              },
              overlay: '',
              classes: 'bg-fill-width',
            },
            classes: '',
            blockClasses: '',
            animate: {
              from: {
                x: 0,
                y: 0,
                rotation: 0,
                scale: 1,
                opacity: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
              },
            },
            style: {
              borderRadius: 'none',
              paddingTop: '0px',
              paddingRight: '0px',
              paddingBottom: '0px',
              paddingLeft: '0px',
              marginTop: '0px',
              marginRight: '0px',
              marginBottom: '0px',
              marginLeft: '0px',
            },
            type: 'layout-builder',
            fullWidth: false,
            elements: [
              {
                row: {
                  xs: 12,
                  sm: 6,
                  md: 6,
                  lg: 6,
                },
                horizontal: 'start',
                vertical: 'stretch',
                gap: {
                  xs: '5',
                  sm: 5,
                  md: 5,
                  lg: 5,
                },
                bg: {
                  img: {
                    src: '',
                    alt: '',
                    classes: 'object-fit',
                  },
                  overlay: '',
                  classes: 'bg-fill-width',
                },
                classes: '',
                blockClasses: '',
                animate: {
                  from: {
                    x: 0,
                    y: 0,
                    rotation: 0,
                    scale: 1,
                    opacity: 1,
                    delay: 0,
                    duration: 1,
                    ease: 'none',
                  },
                  trigger: {
                    onEnter: 'play',
                    onLeave: 'none',
                    onEnterBack: 'none',
                    onLeaveBack: 'none',
                    start: 'top 90%',
                    end: 'top 40%',
                  },
                },
                style: {
                  borderRadius: 'none',
                  paddingTop: '0px',
                  paddingRight: '0px',
                  paddingBottom: '0px',
                  paddingLeft: '0px',
                  marginTop: '0px',
                  marginRight: '0px',
                  marginBottom: '0px',
                  marginLeft: '0px',
                },
                elements: [
                  {
                    type: 'card-1v1',
                    link: {
                      href: '#',
                      label: '信使WEB BUILDER 新增自定义组件流程',
                    },
                    user: '表歌',
                    time: '2022/09/27',
                    feature: {
                      fullIcon: 'fullscreen',
                      openIcon: 'open_in_new',
                      link: '#',
                      ratios: 'media-4-3',
                      img: {
                        classes: 'object-fit',
                        src: '/assets/images/hero/bg01.jpg',
                        alt: 'alt',
                        style: {
                          width: 'auto',
                          height: 'auto',
                          opacity: 1,
                          borderRadius: 0,
                          boxShadow: 'none',
                          objectFit: 'initial',
                        },
                      },
                      style: {
                        width: 'auto',
                        height: 'auto',
                        opacity: 1,
                        borderRadius: 0,
                        boxShadow: 'none',
                        objectFit: 'initial',
                      },
                      src: '/assets/images/hero/bg01.jpg',
                    },
                    moreLabel: '查看更多',
                    style: {
                      width: 'auto',
                      height: 'auto',
                      opacity: 1,
                      borderRadius: 0,
                      boxShadow: 'none',
                      objectFit: 'initial',
                    },
                    src: '/assets/images/hero/bg01.jpg',
                    label: '<p>信使WEB BUILDER 新增自定义组件流程</p>',
                  },
                  {
                    type: 'card-1v1',
                    link: {
                      href: '#',
                      label: 'GITHUB 22 端口连接超时报错的解决办法',
                    },
                    user: '表歌',
                    time: '2022/09/27',
                    feature: {
                      fullIcon: 'fullscreen',
                      openIcon: 'open_in_new',
                      link: '#',
                      ratios: 'media-4-3',
                      img: {
                        classes: 'object-fit',
                        src: '/assets/images/showcase/5.jpg',
                        alt: 'alt',
                        style: {
                          width: 'auto',
                          height: 'auto',
                          opacity: '1',
                          borderRadius: 0,
                          boxShadow: 'none',
                          objectFit: 'initial',
                        },
                      },
                    },
                    moreLabel: '查看更多',
                    style: {
                      width: 'auto',
                      height: 'auto',
                      opacity: 1,
                      borderRadius: 0,
                      boxShadow: 'none',
                      objectFit: 'initial',
                    },
                    src: '/assets/images/hero/bg05.jpg',
                  },
                ],
              },
              {
                row: {
                  xs: 12,
                  sm: 6,
                  md: 6,
                  lg: 6,
                },
                horizontal: 'start',
                vertical: 'stretch',
                gap: {
                  xs: 5,
                  sm: 5,
                  md: 5,
                  lg: 8,
                },
                bg: {
                  img: {
                    src: '',
                    alt: '',
                    classes: 'object-fit',
                  },
                  overlay: '',
                  classes: 'bg-fill-width',
                },
                classes: '',
                blockClasses: '',
                animate: {
                  from: {
                    x: 0,
                    y: 0,
                    rotation: 0,
                    scale: 1,
                    opacity: 1,
                    delay: 0,
                    duration: 1,
                    ease: 'none',
                  },
                  trigger: {
                    onEnter: 'play',
                    onLeave: 'none',
                    onEnterBack: 'none',
                    onLeaveBack: 'none',
                    start: 'top 90%',
                    end: 'top 40%',
                  },
                },
                style: {
                  borderRadius: 'none',
                  paddingTop: '0px',
                  paddingRight: '0px',
                  paddingBottom: '0px',
                  paddingLeft: '0px',
                  marginTop: '0px',
                  marginRight: '0px',
                  marginBottom: '0px',
                  marginLeft: '0px',
                },
                elements: [
                  {
                    type: 'card-1v1',
                    link: {
                      href: '#',
                      label: '信使WEB BUILDER 新增历史版本',
                    },
                    user: '表歌',
                    time: '2022/09/27',
                    feature: {
                      fullIcon: 'fullscreen',
                      openIcon: 'open_in_new',
                      link: '#',
                      ratios: 'media-4-3',
                      img: {
                        classes: 'object-fit',
                        src: '/assets/images/hero/bg02.jpg',
                        alt: 'alt',
                        style: {
                          width: 'auto',
                          height: 'auto',
                          opacity: 1,
                          borderRadius: 0,
                          boxShadow: 'none',
                          objectFit: 'initial',
                        },
                      },
                    },
                    moreLabel: '查看更多',
                    style: {
                      width: 'auto',
                      height: 'auto',
                      opacity: 1,
                      borderRadius: 0,
                      boxShadow: 'none',
                      objectFit: 'initial',
                    },
                    src: '/assets/images/hero/bg02.jpg',
                  },
                  {
                    type: 'card-1v1',
                    link: {
                      href: '#',
                      label: '信使 UI 应用初始化及页面渲染流程',
                    },
                    user: '表歌',
                    time: '2022/09/27',
                    feature: {
                      fullIcon: 'fullscreen',
                      openIcon: 'open_in_new',
                      link: '#',
                      ratios: 'media-4-3',
                      img: {
                        classes: 'object-fit',
                        src: '/assets/images/showcase/6.jpg',
                        alt: 'alt',
                        style: {
                          width: 'auto',
                          height: 'auto',
                          opacity: 1,
                          borderRadius: 0,
                          boxShadow: 'none',
                          objectFit: 'initial',
                        },
                      },
                    },
                    moreLabel: '查看更多',
                    style: {
                      width: 'auto',
                      height: 'auto',
                      opacity: 1,
                      borderRadius: 0,
                      boxShadow: 'none',
                      objectFit: 'initial',
                    },
                    src: '/assets/images/showcase/7.jpg',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 5,
        },
        horizontal: 'center',
        vertical: 'start',
        alignItems: 'center',
        gap: {
          xs: '4',
          sm: '4',
          md: '4',
          lg: '4',
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        blockClasses: '',
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            type: 'title',
            label:
              '欢迎使用 <strong class="text-primary">Web Builder</strong> 快速构建响应式页面',
            style: 'style-v4',
            classes: 'mat-display-1 bold',
          },
          {
            type: 'text',
            spacer: 'none',
            body: '信使UI是基于 Material 的 Angular 前端框架，丰富的组件可提供优秀的数字创新体验，使用 Web Builder 可以通过拖拽快速构建响应式、多主题的 Web 页面。',
          },
          {
            type: 'btn',
            href: '/node/1',
            target: '_blank',
            label: '了解更多',
            mode: 'raised',
            color: 'primary',
          },
        ],
      },
    ],
  },
};

export const Section5A: Story = {};
Section5A.storyName = '5A';
Section5A.args = {
  pageIndex: 0,
  content: {
    fullWidth: false,
    spacer: 'md',
    bgClasses: 'bg-shadow bg-fill-width',
    overlay: '',
    classes: '',
    id: '',
    bg: {
      img: {
        src: '/assets/images/bg/bg-01.png',
        classes: 'object-fit',
        alt: 'bg-01',
      },
      classes: 'bg-shadow bg-fill-width',
      overlay: '',
    },
    horizontal: 'center',
    vertical: 'center',
    animate: {
      from: {
        x: 0,
        y: 0,
        rotation: 0,
        scale: 1,
        opacity: 1,
        delay: 0,
        duration: 1,
        ease: 'none',
      },
      trigger: {
        onEnter: 'play',
        onLeave: 'none',
        onEnterBack: 'none',
        onLeaveBack: 'none',
        start: 'top 90%',
        end: 'top 40%',
      },
    },
    type: 'layout-builder',
    elements: [
      {
        row: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 8,
        },
        horizontal: 'center',
        vertical: 'center',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: 'text-center',
        blockClasses: '',
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        elements: [
          {
            type: 'title',
            label:
              '欢迎使用 <strong class="text-primary">Web Builder</strong> 快速构建响应式页面',
            style: 'style-v4',
            classes: 'mat-display-1 bold',
          },
          {
            type: 'text',
            spacer: 'none',
            body: '信使UI是基于 Material 的 Angular 前端框架，丰富的组件可提供优秀的数字创新体验，使用 Web Builder 可以通过拖拽快速构建响应式、多主题的 Web 页面。',
          },
          {
            horizontal: 'center',
            vertical: 'center',
            gap: {
              xs: '4',
              sm: '4',
              md: '4',
              lg: '4',
            },
            wrapperClass: 'sm:flex-nowrap',
            animate: {
              from: {
                x: 0,
                y: 0,
                rotation: 0,
                scale: 1,
                opacity: 1,
                delay: 0,
                duration: 1,
                ease: 'none',
              },
              trigger: {
                onEnter: 'play',
                onLeave: 'none',
                onEnterBack: 'none',
                onLeaveBack: 'none',
                start: 'top 90%',
                end: 'top 40%',
              },
            },
            row: {
              xs: 12,
              sm: 12,
              md: 12,
              lg: 12,
            },
            bg: {
              img: {
                src: '',
                alt: '',
                classes: 'object-fit',
              },
              overlay: '',
              classes: 'bg-fill-width',
            },
            classes: '',
            blockClasses: '',
            style: {
              borderRadius: 'none',
              paddingTop: '0px',
              paddingRight: '0px',
              paddingBottom: '0px',
              paddingLeft: '0px',
              marginTop: '0px',
              marginRight: '0px',
              marginBottom: '0px',
              marginLeft: '0px',
            },
            type: 'layout-builder',
            spacer: 'md',
            fullWidth: false,
            elements: [
              {
                row: {
                  xs: 12,
                  sm: 4,
                  md: 4,
                  lg: 4,
                },
                horizontal: 'flex-start',
                vertical: 'flex-start',
                bg: {
                  img: {
                    src: '',
                    classes: 'object-fit',
                    alt: '',
                  },
                  overlay: '',
                  classes: 'bg-fill-width',
                },
                classes: '',
                style: {
                  paddingTop: '0px',
                  paddingRight: '0px',
                  paddingBottom: '0px',
                  paddingLeft: '0px',
                  marginTop: '0px',
                  marginRight: '0px',
                  marginBottom: '0px',
                  marginLeft: '0px',
                },
                animate: {
                  from: {
                    x: 0,
                    y: 0,
                    rotation: 0,
                    scale: 1,
                    delay: 0,
                    duration: 1,
                    ease: 'none',
                  },
                  trigger: {
                    onEnter: 'play',
                    onLeave: 'none',
                    onEnterBack: 'none',
                    onLeaveBack: 'none',
                    start: 'top 90%',
                    end: 'top 40%',
                  },
                },
                elements: [
                  {
                    type: 'box',
                    img: {
                      src: '/assets/images/svg/Asset187.svg',
                      alt: 'browser',
                    },
                    style: 'style-v3 use-image',
                    title: {
                      href: '#',
                      label: '高性能',
                    },
                    content:
                      '默认情况下，Drupal 运行速度很快，您可以优化部署，使其运行得更快；',
                  },
                ],
              },
              {
                row: {
                  xs: 12,
                  sm: 4,
                  md: 4,
                  lg: 4,
                },
                horizontal: 'center',
                vertical: 'center',
                bg: {
                  img: {
                    src: '',
                    alt: '',
                    classes: 'object-fit',
                  },
                  overlay: '',
                  classes: 'bg-fill-width',
                },
                classes: '',
                blockClasses: '',
                style: {
                  borderRadius: 'none',
                  paddingTop: '0px',
                  paddingRight: '0px',
                  paddingBottom: '0px',
                  paddingLeft: '0px',
                  marginTop: '0px',
                  marginRight: '0px',
                  marginBottom: '0px',
                  marginLeft: '0px',
                },
                animate: {
                  from: {
                    x: 0,
                    y: 0,
                    rotation: 0,
                    scale: 1,
                    opacity: 1,
                    delay: 0,
                    duration: 1,
                    ease: 'none',
                  },
                  trigger: {
                    onEnter: 'play',
                    onLeave: 'none',
                    onEnterBack: 'none',
                    onLeaveBack: 'none',
                    start: 'top 90%',
                    end: 'top 40%',
                  },
                },

                elements: [
                  {
                    type: 'box',
                    img: {
                      src: '/assets/images/svg/Asset187.svg',
                      alt: 'browser',
                    },
                    style: 'style-v3 use-image',
                    title: {
                      href: '#',
                      label: '易用的编辑器',
                    },
                    content:
                      '通过友好的预览、拖放媒体提高内容编辑的易用性，高效的工作；',
                  },
                ],
              },
              {
                row: {
                  xs: 12,
                  sm: 4,
                  md: 4,
                  lg: 4,
                },
                horizontal: 'center',
                vertical: 'center',
                bg: {
                  img: {
                    src: '',
                    classes: 'object-fit',
                    alt: '',
                  },
                  overlay: '',
                  classes: 'bg-fill-width',
                },
                classes: '',
                style: {
                  paddingTop: '0px',
                  paddingRight: '0px',
                  paddingBottom: '0px',
                  paddingLeft: '0px',
                  marginTop: '0px',
                  marginRight: '0px',
                  marginBottom: '0px',
                  marginLeft: '0px',
                },
                animate: {
                  from: {
                    x: 0,
                    y: 0,
                    rotation: 0,
                    scale: 1,
                    delay: 0,
                    duration: 1,
                    ease: 'none',
                  },
                  trigger: {
                    onEnter: 'play',
                    onLeave: 'none',
                    onEnterBack: 'none',
                    onLeaveBack: 'none',
                    start: 'top 90%',
                    end: 'top 40%',
                  },
                },
                elements: [
                  {
                    type: 'box',
                    img: {
                      src: '/assets/images/svg/Asset187.svg',
                      alt: 'browser',
                    },
                    style: 'style-v3 use-image',
                    title: {
                      href: '#',
                      label: '多语言',
                    },
                    content:
                      'Drupal 100多种语言提供了无以伦比的支持和翻译工作流程； ',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        row: {
          xs: 12,
          sm: 12,
          md: 6,
          lg: 4,
        },
        horizontal: 'center',
        vertical: 'center',
        gap: {
          xs: 0,
          sm: 0,
          md: 0,
          lg: 0,
        },
        bg: {
          img: {
            src: '',
            alt: '',
            classes: 'object-fit',
          },
          overlay: '',
          classes: 'bg-fill-width',
        },
        classes: '',
        blockClasses: '',
        style: {
          borderRadius: 'none',
          paddingTop: '0px',
          paddingRight: '0px',
          paddingBottom: '0px',
          paddingLeft: '0px',
          marginTop: '0px',
          marginRight: '0px',
          marginBottom: '0px',
          marginLeft: '0px',
        },
        animate: {
          from: {
            x: 0,
            y: 0,
            rotation: 0,
            scale: 1,
            opacity: 1,
            delay: 0,
            duration: 1,
            ease: 'none',
          },
          trigger: {
            onEnter: 'play',
            onLeave: 'none',
            onEnterBack: 'none',
            onLeaveBack: 'none',
            start: 'top 90%',
            end: 'top 40%',
          },
        },
        elements: [
          {
            type: 'img',
            hostClasses: 'text-center',
            classes: '',
            src: '/assets/images/illustration/11.png',
            alt: 'alt',
            style: {
              width: '85%',
              height: 'auto',
              opacity: '1',
              borderRadius: '0px',
              boxShadow: 'none',
              aspectRatio: '2 / 3',
              objectFit: 'contain',
            },
          },
        ],
      },
    ],
  },
};
