name: Build app and deploy to xinshi

on:
  push:
    branches: [master]

jobs:
  build:
    # using Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
        # 使用 node:10
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: NPM Install
        run: npm install
      - name: NPM Install Angular
        run: npm install -g @angular/cli > /dev/null
      - name: NPM build Angular Production
        run: ng build --prod --aot=true --source-map --buildOptimizer=true && ng run xinshi:server:production
      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.KEY }}
          ARGS: -avz --delete
          SERVER_PORT: "22"
          FOLDER: "dist"
          SERVER_IP: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          SERVER_DESTINATION: ${{ secrets.XINSHI_PATH }}
